apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && files.all.exists(path, path.matches('.tekton/pipeline.yaml$|.tekton/trustee-fbc-4-18-.*.yaml$|v4.18/Dockerfile$|v4.18/.*/catalog.json$'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee-fbc-4-18
    appstudio.openshift.io/component: trustee-fbc-4-18
    pipelines.appstudio.openshift.io/type: build
  name: trustee-fbc-4-18-on-pull-request
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee-fbc-4-18:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: path-context
    value: v4.18
  - name: dockerfile
    value: v4.18/Dockerfile
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  pipelineRef:
    params:
    - name: name
      value: fbc-builder
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:5de133f1fcb370abd451b0c332e6f19e1bb7b1efe02ebee352e2501e8bfd0723
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
