apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && files.all.exists(path, path.matches('.tekton/pipeline.yaml$|.tekton/trustee-fbc-4-18-.*.yaml$|v4.18/Dockerfile$|v4.18/.*/catalog.json$'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee-fbc-4-18
    appstudio.openshift.io/component: trustee-fbc-4-18
    pipelines.appstudio.openshift.io/type: build
  name: trustee-fbc-4-18-on-push
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee-fbc-4-18:{{revision}}
  - name: path-context
    value: v4.18
  - name: dockerfile
    value: v4.18/Dockerfile
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  pipelineRef:
    params:
    - name: name
      value: fbc-builder
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:f59a8bc8296f789d7790f795a95478c0f24d9691ebb6c6a08c1b4268a34ec062
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-trustee-fbc-4-18
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
