apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && files.all.exists(path, path.matches('.tekton/pipeline.yaml$|.tekton/trustee-fbc-4-19-.*.yaml$|v4.19/Dockerfile$|v4.19/.*/catalog.json$'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee-fbc-4-19
    appstudio.openshift.io/component: trustee-fbc-4-19
    pipelines.appstudio.openshift.io/type: build
  name: trustee-fbc-4-19-on-push
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee-fbc-4-19:on-pr-{{revision}}
  - name: path-context
    value: v4.19
  - name: dockerfile
    value: v4.19/Dockerfile
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  pipelineRef:
    params:
    - name: name
      value: fbc-builder
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:b916bc77bd1965a0ac4d6613e9b1be010a473f641572271ecf1b6024a1653560
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
