apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/trustee-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "push" &&
      target_branch == "main" &&
      files.all.exists(path, path.matches('.tekton/pipeline.yaml$|.tekton/trustee-fbc-4-17-.*.yaml$|v4.17/Dockerfile$|v4.17/.*/catalog.json$'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: trustee-fbc-4-17
    appstudio.openshift.io/component: trustee-fbc-4-17
    pipelines.appstudio.openshift.io/type: build
  name: trustee-fbc-4-17-on-push
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/trustee-fbc-4-17:{{revision}}
  - name: path-context
    value: v4.17
  - name: dockerfile
    value: v4.17/Dockerfile
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/s390x
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: fbc-builder
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:a293a526c1bfe22ec3f190353371d5907a32badb4254f534b1a8f704c9a412be
    - name: kind
      value: pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
